import type { TutorialStep } from "./types";

export const PC_TUTORIAL_STEPS: TutorialStep[] = [
  {
    id: "pc-step-welcome",
    version: "pc",
    stepNumber: 1,
    totalSteps: 8,
    titleKey: "tutorial.pc.step1.title",
    titleFallback: "歡迎使用 E-LAB 電路實驗室！",
    descKey: "tutorial.pc.step1.desc",
    descFallback: "本指引將帶領你一步步搭建並模擬一個標準的「三相馬達自鎖控制電路」。你可以透過左側元件庫放置器件、畫布接線，並切換到運行模式點動控制馬達！",
    tipKey: "tutorial.pc.step1.tip",
    tipFallback: "提示：隨時可點擊「下一步」依序學習，或點擊「🚀 載入本步電路」同步操作。",
    targetSelector: ".brand",
    badgeKey: "tutorial.badge.intro",
    badgeFallback: "新手起步",
    stage: "overview",
  },
  {
    id: "pc-step-palette",
    version: "pc",
    stepNumber: 2,
    totalSteps: 8,
    titleKey: "tutorial.pc.step2.title",
    titleFallback: "認識元件庫與畫布放置",
    descKey: "tutorial.pc.step2.desc",
    descFallback: "左側為「元件庫 (Palette)」，分類提供了三相電源、隔離開關、控制變壓器、接觸器、按鈕及馬達等器件。點選元件後在畫布上點擊即可放置，選中後按「R」可旋轉，「Delete」可刪除。",
    tipKey: "tutorial.pc.step2.tip",
    tipFallback: "快捷鍵：⌘Z 復原、⌘Shift+Z 重做、⌘G 分組、方向鍵可微調位置。",
    targetSelector: ".palette",
    badgeKey: "tutorial.badge.palette",
    badgeFallback: "元件庫",
    stage: "overview",
  },
  {
    id: "pc-step-power",
    version: "pc",
    stepNumber: 3,
    totalSteps: 8,
    titleKey: "tutorial.pc.step3.title",
    titleFallback: "第 1 步：主電源與隔離開關",
    descKey: "tutorial.pc.step3.desc",
    descFallback: "首先在主迴路上方放置「三相電源 (3Φ Mains)」與「隔離開關 (Main Disconnect Breaker)」，並將 L1、L2、L3 與接地 PE 端子依序相連，為整個電路提供總電源隔離與保護。",
    tipKey: "tutorial.pc.step3.tip",
    tipFallback: "接線方法：鼠標點擊元件端子（小圓圈），拉出導線點擊目標端子即可完成接線。",
    targetSelector: ".paper-wrap",
    badgeKey: "tutorial.badge.power",
    badgeFallback: "主迴路電源",
    stage: "power",
    actionType: "apply-circuit",
  },
  {
    id: "pc-step-transformer",
    version: "pc",
    stepNumber: 4,
    totalSteps: 8,
    titleKey: "tutorial.pc.step4.title",
    titleFallback: "第 2 步：控制電源與變壓器",
    descKey: "tutorial.pc.step4.desc",
    descFallback: "從主線引出 L1、L2 兩相至「控制變壓器 (Transformer)」高壓側 H1、H2，將 480V/380V 降壓為 120V 安全控制電壓。低壓側 X1 經熔斷器 FU1/FU2 引出 A1、A2 控制母線，X2 接地至 PE 形成標準保護回路。",
    tipKey: "tutorial.pc.step4.tip",
    tipFallback: "端子標籤：變壓器左側標記 H1/H2，右側標記 X1/X2，接地 PE 與電源端共地不短路。",
    targetSelector: ".paper-wrap",
    badgeKey: "tutorial.badge.transformer",
    badgeFallback: "控制電源",
    stage: "transformer",
    actionType: "apply-circuit",
  },
  {
    id: "pc-step-control",
    version: "pc",
    stepNumber: 5,
    totalSteps: 8,
    titleKey: "tutorial.pc.step5.title",
    titleFallback: "第 3 步：自鎖控制核心（按鈕與接觸器）",
    descKey: "tutorial.pc.step5.desc",
    descFallback: "在 A1-A2 控制母線間，串聯「常閉停止按鈕 Stop (SB1)」與「常開起動按鈕 Start (SB2)」至接觸器線圈「M1 (KM1)」。將接觸器的常開輔助觸點「M1 (Aux-NO)」與起動按鈕並聯，形成經典的「自保持自鎖迴路」。",
    tipKey: "tutorial.pc.step5.tip",
    tipFallback: "自鎖原理：當按下起動按鈕時線圈得電，輔助常開觸點閉合；鬆開按鈕後電流改由輔助觸點持續供電！",
    targetSelector: ".paper-wrap",
    badgeKey: "tutorial.badge.control",
    badgeFallback: "自鎖控制",
    stage: "control",
    actionType: "apply-circuit",
  },
  {
    id: "pc-step-motor",
    version: "pc",
    stepNumber: 6,
    totalSteps: 8,
    titleKey: "tutorial.pc.step6.title",
    titleFallback: "第 4 步：連接三相馬達與過載保護",
    descKey: "tutorial.pc.step6.desc",
    descFallback: "在主迴路下方串接接觸器主觸點「M1 (Main)」、熱過載繼電器「OL1 (Overload)」，最後三相線條直連至「三相馬達 M1」。當接觸器吸合時，三相動力電源將直接驅動馬達旋轉。",
    tipKey: "tutorial.pc.step6.tip",
    tipFallback: "佈線對齊：元件端子均遵循標準網格間距，水平連接時導線會呈現乾淨的水平直線。",
    targetSelector: ".paper-wrap",
    badgeKey: "tutorial.badge.motor",
    badgeFallback: "動力負載",
    stage: "motor",
    actionType: "apply-circuit",
  },
  {
    id: "pc-step-run",
    version: "pc",
    stepNumber: 7,
    totalSteps: 8,
    titleKey: "tutorial.pc.step7.title",
    titleFallback: "第 5 步：切換運行模式並啟動仿真",
    descKey: "tutorial.pc.step7.desc",
    descFallback: "點擊頂部工具列的「RUN」切換為運行模式。首先點擊合上主隔離開關 (Main Disconnect Breaker)，接著點擊常開起動按鈕「Start (SB2)」，觀察接觸器吸合、自鎖維持，三相馬達高速旋轉！",
    tipKey: "tutorial.pc.step7.tip",
    tipFallback: "交互操作：點擊「Stop」按鈕可隨時切斷迴路停機；右側 Inspector 面板可即時監控馬達轉速與工藝變量。",
    targetSelector: ".mode-switch",
    badgeKey: "tutorial.badge.run",
    badgeFallback: "仿真運行",
    stage: "run",
    actionType: "switch-run",
  },
  {
    id: "pc-step-complete",
    version: "pc",
    stepNumber: 8,
    totalSteps: 8,
    titleKey: "tutorial.pc.step8.title",
    titleFallback: "🎉 恭喜！你已掌握三相馬達控制電路",
    descKey: "tutorial.pc.step8.desc",
    descFallback: "你已經學會了電源配置、控制變壓器降壓、按鈕自鎖與電機驅動！你可以自由修改電路、添加故障注入、使用 File 選單列印或存檔。隨時可點擊 Examples 左側的「✨ 指引」按鈕重新演練。",
    tipKey: "tutorial.pc.step8.tip",
    tipFallback: "進階提示：使用頂部的縮放滑動條或「適應屏幕 (Zoom Fit)」可讓電路完美契合你的螢幕！",
    targetSelector: ".top-actions",
    badgeKey: "tutorial.badge.complete",
    badgeFallback: "完成指引",
    stage: "complete",
  },
];

export const MOBILE_TUTORIAL_STEPS: TutorialStep[] = [
  {
    id: "mobile-step-welcome",
    version: "mobile",
    stepNumber: 1,
    totalSteps: 7,
    titleKey: "tutorial.mobile.step1.title",
    titleFallback: "歡迎使用 E-LAB 移動端！",
    descKey: "tutorial.mobile.step1.desc",
    descFallback: "本指引將帶你在手機/平板觸控設備上，透過觸控手勢、抽屜面板與底部快捷欄，完成「三相馬達自鎖控制電路」的搭建與仿真！",
    tipKey: "tutorial.mobile.step1.tip",
    tipFallback: "手勢操作：單指拖動畫布平移，雙指捏合縮放 (Pinch-to-zoom)。",
    targetSelector: ".brand",
    badgeKey: "tutorial.badge.intro",
    badgeFallback: "觸控指引",
    stage: "overview",
  },
  {
    id: "mobile-step-drawer",
    version: "mobile",
    stepNumber: 2,
    totalSteps: 7,
    titleKey: "tutorial.mobile.step2.title",
    titleFallback: "頂部按鈕與滑動抽屜",
    descKey: "tutorial.mobile.step2.desc",
    descFallback: "點擊頂部「[☰]」可展開左側元件庫抽屜選取器件；點擊「[⚙]」可打開右側屬性與工作台；點擊「[⋯]」可開啟功能選單進行存檔、切換範例與列印。",
    tipKey: "tutorial.mobile.step2.tip",
    tipFallback: "抽屜操作：點擊遮罩或右上角 ✕ 即可快速收起抽屜。",
    targetSelector: ".mobile-header-actions",
    badgeKey: "tutorial.badge.drawer",
    badgeFallback: "抽屜導航",
    stage: "overview",
  },
  {
    id: "mobile-step-touch-place",
    version: "mobile",
    stepNumber: 3,
    totalSteps: 7,
    titleKey: "tutorial.mobile.step3.title",
    titleFallback: "元件放置與觸控接線",
    descKey: "tutorial.mobile.step3.desc",
    descFallback: "從元件庫點選器件後在畫布上輕觸即可放置。端子擁有大尺寸透明觸控熱區，手指輕觸端子即可拉出導線並自動吸附目標端子！",
    tipKey: "tutorial.mobile.step3.tip",
    tipFallback: "快捷操作：長按元件 500ms 喚出快捷選單，或使用畫布底部浮動工具欄進行旋轉、翻轉與刪除。",
    targetSelector: ".paper-wrap",
    badgeKey: "tutorial.badge.touch",
    badgeFallback: "觸控接線",
    stage: "power",
    actionType: "apply-circuit",
  },
  {
    id: "mobile-step-circuit-building",
    version: "mobile",
    stepNumber: 4,
    totalSteps: 7,
    titleKey: "tutorial.mobile.step4.title",
    titleFallback: "三相馬達控制電路核心結構",
    descKey: "tutorial.mobile.step4.desc",
    descFallback: "電路包含：① 三相電源與隔離開關 ② 控制變壓器降壓保護 ③ 常閉停止按鈕 Stop ④ 常開起動按鈕 Start 與接觸器輔助觸點並聯自鎖 ⑤ 三相馬達與熱過載保護。",
    tipKey: "tutorial.mobile.step4.tip",
    tipFallback: "點擊下方「🚀 載入完整電路」可立即在圖紙上生成標準工藝接線。",
    targetSelector: ".paper-wrap",
    badgeKey: "tutorial.badge.circuit",
    badgeFallback: "核心結構",
    stage: "motor",
    actionType: "apply-circuit",
  },
  {
    id: "mobile-step-run-mode",
    version: "mobile",
    stepNumber: 5,
    totalSteps: 7,
    titleKey: "tutorial.mobile.step5.title",
    titleFallback: "切換 RUN 模式進行觸控仿真",
    descKey: "tutorial.mobile.step5.desc",
    descFallback: "點擊頂部「[RUN]」按鈕切換為運行模式。在畫布上輕觸點擊合上主隔離開關 (Main Disconnect Breaker)，導線將立即亮起動態電流指示！",
    tipKey: "tutorial.mobile.step5.tip",
    tipFallback: "觸覺反饋：在支援的手機上，操作工控開關與按鈕時享有真實震動回饋！",
    targetSelector: ".mode-switch",
    badgeKey: "tutorial.badge.run",
    badgeFallback: "運行模式",
    stage: "run",
    actionType: "switch-run",
  },
  {
    id: "mobile-step-motor-start",
    version: "mobile",
    stepNumber: 6,
    totalSteps: 7,
    titleKey: "tutorial.mobile.step6.title",
    titleFallback: "輕觸 Start 按鈕，啟動馬達！",
    descKey: "tutorial.mobile.step6.desc",
    descFallback: "在畫布上點擊常開起動按鈕「Start (SB2)」。接觸器線圈 KM1 得電吸合，自鎖觸點閉合，三相馬達 M1 高速轉動！點擊「Stop (SB1)」可隨時切斷控制電路停止馬達。",
    tipKey: "tutorial.mobile.step6.tip",
    tipFallback: "一鍵適應：點擊底部工具列的「[⛶ 適應屏幕]」按鈕，可自動讓電路在手機螢幕中居中完整顯示！",
    targetSelector: ".paper-wrap",
    badgeKey: "tutorial.badge.start",
    badgeFallback: "馬達運轉",
    stage: "running-latch",
  },
  {
    id: "mobile-step-complete",
    version: "mobile",
    stepNumber: 7,
    totalSteps: 7,
    titleKey: "tutorial.mobile.step7.title",
    titleFallback: "🎉 移動端指引完成！",
    descKey: "tutorial.mobile.step7.desc",
    descFallback: "你已經熟練掌握了移動設備上的觸控電路搭建與仿真！點擊頂部「[⋯]」選單可隨時存檔、匯出或列印圖紙。隨時可在頂部或選單中重新啟動本指引。",
    tipKey: "tutorial.mobile.step7.tip",
    tipFallback: "提示：切換至橫屏模式時，畫布可獲得更寬廣的繪圖與仿真視野！",
    targetSelector: ".mobile-header-actions",
    badgeKey: "tutorial.badge.complete",
    badgeFallback: "完成學習",
    stage: "complete",
  },
];
